apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2-storage
parameters:
  type: gp2
  fsType: ext4
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain
allowVolumeExpansion: true
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-example
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2-storage
  awsElasticBlockStore:
    volumeID: vol-0d3e4588c21db0944
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-example
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-example
spec:
  containers:
  - name: container-example
    image: nginx:latest
    volumeMounts:
    - name: pv-example
      mountPath: /usr/share/nginx/html
  volumes:
  - name: pv-example
    persistentVolumeClaim:
      claimName: pvc-example
