apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  name: manual
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
--- 
apiVersion: v1 
kind: PersistentVolume
metadata:
  name: my-ebs-volume 
spec: 
  storageClassName: manual 
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-04432d6e249609735
    fsType: ext4
---
apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: my-ebs-pvc 
spec:
  storageClassName: manual 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests:
      storage: 10Gi 
  volumeName: my-ebs-volume
--- 
apiVersion: v1 
kind: Pod 
metadata: 
  name: example-pod 
spec:
  containers:
    - name: my-cont 
      image: nginx 
      volumeMounts:
        - name: my-ebs-volume 
          mountPath: /usr/share/nginx/html
  volumes:
    - name: my-ebs-volume 
      persistentVolumeClaim:
        claimName: my-ebs-pvc 