apiVersion: apps/v1 
kind: ReplicaSet 
metadata:
  name: wipro-app-rs
spec: # It is going to define the behaviour of the replicaset
  replicas: 5
  selector:
    matchLabels:
       app: oracle 
  template:
    metadata:
      labels:
        app: oracle 
    spec: # It is going to define the behaviour of the pod 
      containers:
        - name: oracle-app 
          image: docker.io/muralisocial123/wipro-web-app:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi 
            limits: 
              cpu: 200m
              memory: 256Mi    

            
  