apiVersion: v1 
kind: Pod 
metadata:
  name: example-pod 
spec:
  containers:
    - name: my-container 
      image: busybox 
      command: ["sleep", "3600"]
      envFrom:
        - configMapRef:
            name: my-config 
        